@Plate.Api_HostAddress = https://localhost:7146

# @name login
POST {{Plate.Api_HostAddress}}/login
accept: */*
Content-Type: application/json

{
  "Username": "batman",
  "Password": "batman"
}
###

@authToken = {{login.response.body.$.token}}

# @name getAuthenticated
GET {{Plate.Api_HostAddress}}/api/weatherforecast/authenticated 
Authorization: Bearer
accept: */*
###