@Plate.Api_HostAddress = https://localhost:7146

# @name login
POST {{Plate.Api_HostAddress}}/login
accept: */*
Content-Type: application/json

{
  "Username": "batman",
  "Password": "batman"
}
###

@tokenNovo = {{login.response.body.$.token}}

# @name autenticado
GET {{Plate.Api_HostAddress}}/api/weatherforecast/authenticated
accept: application/json
Authorization: Bearer {{tokenNovo}}
###

# @name NaoAutenticado
GET {{Plate.Api_HostAddress}}/api/weatherforecast
accept: */*
###